---
apiVersion: v1
kind: Service
metadata:
  name: testodogwu-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
    nodePort: 31770
  selector:
    app: testodogwu-fe
  type: NodePort


